name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your preferred Node.js version
          cache: 'npm' # Cache node_modules to speed up builds

      - name: Install dependencies
        run: npm ci # Use npm ci for faster and more reliable installs

      - name: Install react-native CLI dependencies
        run: |
          npm install -g react-native-cli # If react-native CLI is not globally installed yet

      - name: Build for iOS
        run: npm run build-ios # You should have this custom script in your package.json for iOS

      - name: Build for Android
        run: npm run build-android # You should have this custom script in your package.json for Android

      - name: Run tests
        run: npm test # Or your test command (e.g., npm test, yarn test)

      # Example deployment step (adjust as needed)
      - name: Deploy to Production (Example)
        if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here (e.g., SSH, rsync, cloud provider CLI)
          # Example: ssh user@yourserver "bash deploy.sh"
